//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BitirmeProjesi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Connection
    {
        public int Id { get; set; }
        public string ConnectionId { get; set; }
        public bool isConnected { get; set; }
        public int UserId { get; set; }
        public int GroupChatId { get; set; }
    
        public virtual GroupChat GroupChat { get; set; }
        public virtual User User { get; set; }
    }
}
