
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace BitirmeProjesi.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Event
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Event()
    {

        this.GroupMembers = new HashSet<GroupMember>();

        this.EventNews = new HashSet<EventNews>();

    }


    public int EventId { get; set; }

    public System.DateTime EventCreateDate { get; set; }

    public System.DateTime EventUpdateDate { get; set; }

    public string EventDefinition { get; set; }

    public string EventTopic { get; set; }

    public string EventLocation { get; set; }

    public System.DateTime EventBeginDate { get; set; }

    public byte[] EventThumbnail { get; set; }

    public int EventGroup { get; set; }

    public System.DateTime EventTime { get; set; }



    public virtual Group Group { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<GroupMember> GroupMembers { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<EventNews> EventNews { get; set; }

}

}
