
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace BitirmeProjesi.Models
{

using System;
    using System.Collections.Generic;
    
public partial class EventNewsFile
{

    public int Id { get; set; }

    public byte[] FileContent { get; set; }

    public int EventNewsEventNewsId { get; set; }



    public virtual EventNews EventNew { get; set; }

}

}
