
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace BitirmeProjesi.Models
{

using System;
    using System.Collections.Generic;
    
public partial class GroupChatMessage
{

    public int ChatMessageId { get; set; }

    public string ChatMessage { get; set; }

    public System.DateTime PostDate { get; set; }

    public string Username { get; set; }

    public int GroupChatId { get; set; }



    public virtual GroupChat GroupChat { get; set; }

}

}
