
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace BitirmeProjesi.Models
{

using System;
    using System.Collections.Generic;
    
public partial class GroupChat
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public GroupChat()
    {

        this.Connections = new HashSet<Connection>();

        this.GroupChatMessages = new HashSet<GroupChatMessage>();

    }


    public int GroupChatId { get; set; }

    public string GroupChatName { get; set; }

    public bool IsPublic { get; set; }

    public int GroupId { get; set; }



    public virtual Group Group { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Connection> Connections { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<GroupChatMessage> GroupChatMessages { get; set; }

}

}
