//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BitirmeProjesi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GroupChat
    {
        public int GroupChatId { get; set; }
        public string GroupChatName { get; set; }
        public bool IsPublic { get; set; }
        public int GroupId { get; set; }
    
        public virtual Group Group { get; set; }
    }
}
