
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace BitirmeProjesi.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Post
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Post()
    {

        this.UploadFiles = new HashSet<UploadFile>();

    }


    public int PostId { get; set; }

    public System.DateTime DateofPost { get; set; }

    public string UserMentions { get; set; }

    public int UserId { get; set; }

    public string ContentofPost { get; set; }

    public Nullable<int> Likes { get; set; }

    public Nullable<int> Dislikes { get; set; }



    public virtual User User { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<UploadFile> UploadFiles { get; set; }

}

}
